In [119]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

masukkan input data 
- x1_data -> x1
- x2_data -> x2

In [120]:
data = np.array([[0.36, 0.47], [0.36, 0.57], [0.15, 0.57], [0.10, 0.78],
                 [0.21, 0.83], [0.41, 0.10], [0.62, 0.05], [0.67, 0.15],
                 [0.93, 0.01], [0.93, 0.05], [0.99, 0.21], [0.57, 0.05],
                 [0.83, 0.83], [0.73, 0.93], [0.57, 0.57], [0.99, 0.57]])
x1_data = data[:,0]
x2_data = data[:,1]

## Fungsi klasifikasi dengan Regresi Linear
$$\begin{aligned}\begin{aligned}\begin{pmatrix}
1.0 & x1_{0} & x2_{0} \\
1.0 & x1_{1} & x2_{1} \\
1.0 & ... & ... \\
1.0 & x1_{n} & x2_{n} \\ \end{pmatrix}\end{aligned}\begin{pmatrix}
w0 \\ w1 \\ w2\end{pmatrix}&=\begin{pmatrix}
+1 \\ ... \\ ... \\ -1 \end{pmatrix} \\
\begin{pmatrix} 
w0 \\ w1 \\ w2 \end{pmatrix} &=
\begin{pmatrix}\begin{pmatrix}
1.0 & 1.0 & ... & 1.0 \\ 
x1_{0} & x1_{1} & ... & x1_{n} \\
x2_{0} & x2_{1} & ... & x2_{n} \end{pmatrix}\begin{pmatrix}
1.0 & x1_{0} & x2_{0} \\
1.0 & x1_{1} & x2_{1} \\
1.0 & ... & ... \\
1.0 & x1_{n} & x2_{n} \\ \end{pmatrix}\end{pmatrix}^{-1}
\begin{pmatrix}
1.0 & 1.0 & ... & 1.0 \\ 
x1_{0} & x1_{1} & ... & x1_{n} \\
x2_{0} & x2_{1} & ... & x2_{n} \end{pmatrix}
\begin{pmatrix}
+1 \\ ... \\ ... \\ -1 \end{pmatrix}\end{aligned}$$

In [121]:
def klasifikasi_regresi_linear(inp, out):
    return np.matmul(np.matmul(np.linalg.inv(np.matmul(inp.T,inp)),inp.T),out)

bentuk input seperti matriks diatas
$$\begin{aligned}\begin{pmatrix}
x1_{0} & x2_{0} \\
x1_{1} & x2_{1} \\
... & ... \\
x1_{n} & x2_{n} \\\end{pmatrix}\end{aligned} \rightarrow
\begin{aligned}\begin{pmatrix}
1.0 & x1_{0} & x2_{0} \\
1.0 & x1_{1} & x2_{1} \\
1.0 & ... & ... \\
1.0 & x1_{n} & x2_{n} \\\end{pmatrix}\end{aligned}$$

In [122]:
jumlah_data, jumlah_kelas = data.shape
bias = np.array([np.ones(jumlah_data)]).T
input_data = np.hstack((bias, data))
input_data

array([[1.  , 0.36, 0.47],
       [1.  , 0.36, 0.57],
       [1.  , 0.15, 0.57],
       [1.  , 0.1 , 0.78],
       [1.  , 0.21, 0.83],
       [1.  , 0.41, 0.1 ],
       [1.  , 0.62, 0.05],
       [1.  , 0.67, 0.15],
       [1.  , 0.93, 0.01],
       [1.  , 0.93, 0.05],
       [1.  , 0.99, 0.21],
       [1.  , 0.57, 0.05],
       [1.  , 0.83, 0.83],
       [1.  , 0.73, 0.93],
       [1.  , 0.57, 0.57],
       [1.  , 0.99, 0.57]])

Klasifikasi lemari dan buffet

In [123]:
#atur input lemari dan buffet saja
kelas_lemari = input_data[0:5,:]
kelas_buffet = input_data[5:12,:]
inp = np.vstack((kelas_lemari, kelas_buffet))

#atur output lemari -> +1 & buffet -> -1
out_lemari = np.array([[1] for _ in range(len(kelas_lemari))])
out_buffet = np.array([[-1] for _ in range(len(kelas_buffet))])
out = np.vstack((out_lemari, out_buffet))

w0 = klasifikasi_regresi_linear(inp,out)
w0 = np.round(w0,2)
w0


array([[-0.69],
       [-0.62],
       [ 2.66]])

Klasifikasi lemari dan wardrope

In [124]:
#atur input lemari dan wardrope saja
kelas_lemari = input_data[0:5,:]
kelas_wardrope = input_data[12:16,:]
inp = np.vstack((kelas_lemari, kelas_wardrope))

#atur output lemari -> +1 & wardrope -> -1
out_lemari = np.array([[1] for _ in range(len(kelas_lemari))])
out_wardrope = np.array([[-1] for _ in range(len(kelas_wardrope))])
out = np.vstack((out_lemari, out_wardrope))

w1 = klasifikasi_regresi_linear(inp,out)
w1 = np.round(w1,2)
w1

array([[ 2.25],
       [-2.93],
       [-1.08]])

Klasifikasi buffet dan wardrope

In [125]:
#atur input lemari dan wardrope saja
kelas_buffet = input_data[5:12,:]
kelas_wardrope = input_data[12:16,:]
inp = np.vstack((kelas_buffet, kelas_wardrope))

#atur output buffet -> +1 & wardrope -> -1
out_buffet = np.array([[1] for _ in range(len(kelas_buffet))])
out_wardrope = np.array([[-1] for _ in range(len(kelas_wardrope))])
out = np.vstack((out_buffet, out_wardrope))

w2 = klasifikasi_regresi_linear(inp,out)
w2 = np.round(w2,2)
w2

array([[ 1.19],
       [-0.03],
       [-2.79]])

## Fungsi Garis Linear
$$y = w_{0}+w_{1}\times x1+w_{2}\times x2$$

In [126]:
garis_linear = lambda w, x: np.matmul(x,w)

Kalkulasi F0 dari w0

In [127]:
y0 = garis_linear(w0,input_data)
y0 = np.round(y0, 2)
y0

array([[ 0.34],
       [ 0.6 ],
       [ 0.73],
       [ 1.32],
       [ 1.39],
       [-0.68],
       [-0.94],
       [-0.71],
       [-1.24],
       [-1.13],
       [-0.75],
       [-0.91],
       [ 1.  ],
       [ 1.33],
       [ 0.47],
       [ 0.21]])

Kalkulasi F1 dari w1

In [128]:
y1 = garis_linear(w1,input_data)
y1 = np.round(y1, 2)
y1

array([[ 0.69],
       [ 0.58],
       [ 1.19],
       [ 1.11],
       [ 0.74],
       [ 0.94],
       [ 0.38],
       [ 0.12],
       [-0.49],
       [-0.53],
       [-0.88],
       [ 0.53],
       [-1.08],
       [-0.89],
       [-0.04],
       [-1.27]])

Kalkulasi F2 dari w2

In [129]:
y2 = garis_linear(w2,input_data)
y2 = np.round(y2, 2)
y2

array([[-0.13],
       [-0.41],
       [-0.4 ],
       [-0.99],
       [-1.13],
       [ 0.9 ],
       [ 1.03],
       [ 0.75],
       [ 1.13],
       [ 1.02],
       [ 0.57],
       [ 1.03],
       [-1.15],
       [-1.43],
       [-0.42],
       [-0.43]])

## Fungsi aktivasi bipolar / hardlim
$$sgn(x)=\begin{cases}
1, \text{if } x>0 \\
0, \text{if } x=0 \\
-1, \text{if } x<0 \end{cases}$$

In [130]:
def aktivasi_hardlim(x):
    out = np.array([1 if x_>0 else (0 if x_==0 else -1) for x_ in x])
    return out

Cari F0, F1, dan F2 dengan memasukkan y0, y1, dan y2 ke fungsi aktivasi_hardlim

In [131]:
F0 = aktivasi_hardlim(y0)
F1 = aktivasi_hardlim(y1)
F2 = aktivasi_hardlim(y2)
print(F0)
print(F1)
print(F2)

[ 1  1  1  1  1 -1 -1 -1 -1 -1 -1 -1  1  1  1  1]
[ 1  1  1  1  1  1  1  1 -1 -1 -1  1 -1 -1 -1 -1]
[-1 -1 -1 -1 -1  1  1  1  1  1  1  1 -1 -1 -1 -1]


buat output untuk labelling

In [132]:
#atur output dengan ukuran sesuai data
jumlah_data, jumlah_kelas = data.shape
output = np.empty(shape=jumlah_data, dtype=object)

Labelling Output F0

In [133]:
batas_lemari = np.arange(0,5)
batas_buffet = np.arange(5,12)
batas = np.append(batas_lemari, batas_buffet)

for i in batas:
    if F0[i] == 1:
        output[i] = "lemari"
    elif F0[i]  == -1:
        output[i] = "buffet"

labelling output F1

In [134]:
batas_lemari = np.arange(0,5)
batas_wardrope = np.arange(12,16)
batas = np.append(batas_lemari, batas_wardrope)

for i in batas:
    if F1[i] == 1:
        output[i] = "lemari"
    elif F1[i]  == -1:
        output[i] = "wardrope"

labelling output F2

In [135]:
batas_buffet = np.arange(5,12)
batas_wardrope = np.arange(12,16)
batas = np.append(batas_buffet, batas_wardrope)

for i in batas:
    if F2[i] == 1:
        output[i] = "buffet"
    elif F2[i]  == -1:
        output[i] = "wardrope"

Buat tabel dengan Pandas DataFrame

In [136]:
df = pd.DataFrame({"x1":x1_data, "x2":x2_data, "y0":(y[0] for y in y0), 
                   "y1":(y[0] for y in y1), "y2":(y[0] for y in y2),
                   "F0":F0, "F1":F1, "F2":F2, "out":output})
# tabel index dimulai dari angka 1
df.index += 1
display(df)

x1    x2    y0    y1    y2  F0  F1  F2       out
1   0.36  0.47  0.34  0.69 -0.13   1   1  -1    lemari
2   0.36  0.57  0.60  0.58 -0.41   1   1  -1    lemari
3   0.15  0.57  0.73  1.19 -0.40   1   1  -1    lemari
4   0.10  0.78  1.32  1.11 -0.99   1   1  -1    lemari
5   0.21  0.83  1.39  0.74 -1.13   1   1  -1    lemari
6   0.41  0.10 -0.68  0.94  0.90  -1   1   1    buffet
7   0.62  0.05 -0.94  0.38  1.03  -1   1   1    buffet
8   0.67  0.15 -0.71  0.12  0.75  -1   1   1    buffet
9   0.93  0.01 -1.24 -0.49  1.13  -1  -1   1    buffet
10  0.93  0.05 -1.13 -0.53  1.02  -1  -1   1    buffet
11  0.99  0.21 -0.75 -0.88  0.57  -1  -1   1    buffet
12  0.57  0.05 -0.91  0.53  1.03  -1   1   1    buffet
13  0.83  0.83  1.00 -1.08 -1.15   1  -1  -1  wardrope
14  0.73  0.93  1.33 -0.89 -1.43   1  -1  -1  wardrope
15  0.57  0.57  0.47 -0.04 -0.42   1  -1  -1  wardrope
16  0.99  0.57  0.21 -1.27 -0.43   1  -1  -1  wardrope